# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
android.enableJetifier=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Non-transitive R class. After turning on: "Cross-module R files need to be forced to specify a package name to resolve resource conflicts."
android.nonTransitiveRClass=false

# After turning it on, you need to pay attention to adding the reflected classes to the confusion-free list.
android.enableR8.fullMode=true

# Whether the resource id is set as a variable, true: the resource id can be dynamically modified during runtime, false: fixes the problem that Java cannot use switch and cannot use R.id
android.nonFinalResIds=false

# Turn on global Build Config
android.buildFeatures.buildConfig=true

# Use BuildConfig in Kotlin to improve compilation speed
android.enableBuildConfigAsBytecode=true

android.injected.testOnly=false
